[package]
name = "pf_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
rand_xoshiro = "0.6"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
wide = "0.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"